### ISSUE TITLE
Bug Visual Minigame Desktop

### ISSUE THREAD

**Issue by EdYuTo** [FellowshipOfTheGame/MulTI-Task#6]
Antes de deslizar para baixo o arquivo teleporta para posicao final por alguns frames e depois volta para cima para poder deslizar.

**Comment by gabrielrspupo** [comment]
Corrigido no commit [d5d684f](https://github.com/FellowshipOfTheGame/MulTI-Task/commit/d5d684fd738b917fe976852bd4da9c52a9644df5).
